name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or any specific version you want

      - name: Install dependencies
        run: yarn

      - name: Build the React app
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
